site_name: Car Rental documentation
pages:
    - Home: index.md
    - Getting Started: gs.md
    - Giving Feedback: feedback.md
    - The Home Screen: home.md
    - Branch Administration: branches.md
    - Type Administration: types.md
    - User Administration: ua.md
    - Reports: reports.md
    - System Backup: backup.md
theme: readthedocs
